[pytest]
asyncio_mode = strict
log_file = test.log
log_format = %(asctime)s %(levelname)s %(filename)s:%(lineno)d %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
log_level = debug

addopts = --strict-markers
markers =
    integration: integration tests
    system: system tests
    production: production tests
    slow: slow tests
    docker: docker dependent tests
    network: network tests