"""Integration tests for HTTP/2 over TLS.

Starts BlackBull with a real TLS certificate, connects with httpx (h2 protocol),
and verifies ALPN negotiation, response correctness, and concurrent multiplexing.

Requires tests/cert.pem and tests/key.pem (generated by conftest.py session fixture).
"""
import asyncio
import json
import pathlib
from multiprocessing import Process

import httpx
import pytest
import pytest_asyncio

from blackbull import BlackBull, JSONResponse, Response
from blackbull.response import StreamingResponse


_CERT = pathlib.Path(__file__).parent.parent / 'cert.pem'
_KEY  = pathlib.Path(__file__).parent.parent / 'key.pem'


def _make_app() -> BlackBull:
    app = BlackBull()

    @app.route(path='/hello')
    async def hello():
        return {'message': 'hello'}

    @app.route(path='/text')
    async def text():
        return Response('hi')

    @app.route(path='/stream')
    async def stream(scope, receive, send):
        async def chunks():
            for chunk in [b'a', b'b', b'c']:
                yield chunk
        await StreamingResponse(chunks())(scope, receive, send)

    return app


def _run(app):
    asyncio.run(app.run())


@pytest_asyncio.fixture
async def h2_app():
    app = _make_app()
    app.create_server(certfile=str(_CERT), keyfile=str(_KEY), port=0)

    p = Process(target=_run, args=(app,))
    p.start()
    app.wait_for_port(timeout=10.0)

    yield app

    app.stop()
    p.terminate()
    p.join(timeout=5)


@pytest.mark.integration
@pytest.mark.asyncio
async def test_http2_json_response(h2_app):
    url = f'https://localhost:{h2_app.port}/hello'
    async with httpx.AsyncClient(http2=True, verify=False) as client:
        r = await client.get(url)
    assert r.status_code == 200
    assert r.http_version == 'HTTP/2'
    assert r.json() == {'message': 'hello'}


@pytest.mark.integration
@pytest.mark.asyncio
async def test_http2_plain_response(h2_app):
    url = f'https://localhost:{h2_app.port}/text'
    async with httpx.AsyncClient(http2=True, verify=False) as client:
        r = await client.get(url)
    assert r.status_code == 200
    assert r.http_version == 'HTTP/2'
    assert r.text == 'hi'


@pytest.mark.integration
@pytest.mark.asyncio
async def test_http2_multiplexed(h2_app):
    """10 concurrent requests on one HTTP/2 connection must all succeed."""
    url = f'https://localhost:{h2_app.port}/hello'
    async with httpx.AsyncClient(http2=True, verify=False) as client:
        responses = await asyncio.gather(*(client.get(url) for _ in range(10)))
    assert all(r.status_code == 200 for r in responses)
    assert all(r.http_version == 'HTTP/2' for r in responses)


@pytest.mark.integration
@pytest.mark.asyncio
async def test_http2_streaming_response(h2_app):
    """StreamingResponse chunks must arrive concatenated and in order."""
    url = f'https://localhost:{h2_app.port}/stream'
    async with httpx.AsyncClient(http2=True, verify=False) as client:
        r = await client.get(url)
    assert r.status_code == 200
    assert r.content == b'abc'
