"""AsyncAPI 3.0 documentation for the MQTT broker — :class:`AsyncAPIExtension`.

OpenAPI documents BlackBull's HTTP surface; it has no vocabulary for topics,
QoS, retain, or the publish/subscribe direction, so the MQTT broker is — by
design — invisible to it.  **AsyncAPI** (https://www.asyncapi.com/) is the
messaging-world counterpart, and this extension emits an AsyncAPI 3.0 document
describing the topic taps the application registered via
``MQTTExtension.on_message``, served over HTTP exactly as ``/openapi.json`` is.

It is a normal :class:`~blackbull.extension.Extension`, parallel to
``OpenAPIExtension`` and coexisting with it::

    app = BlackBull()
    mqtt = app.add_extension(MQTTExtension(port=1883))
    app.add_extension(AsyncAPIExtension(title='Sensor Gateway', version='1.0.0'))

    @mqtt.on_message(topic='sensors/{room}/temperature')
    async def on_temp(msg, room): ...

After ``app.run()`` the document is at ``/asyncapi.json`` and an HTML viewer at
``/asyncapi``.

Honest caveats (also stated in the document's ``info.description``):

1. It documents the **application's taps**, not "the broker's API".  A broker
   accepts any topic from any client; ``on_message`` filters describe only what
   *this* app observes.
2. **QoS / retain are not captured** — ``on_message`` taps regardless of QoS,
   so MQTT channel bindings are omitted until the tap API carries that metadata.
3. **Payloads are opaque bytes** (``application/octet-stream``) until an
   optional ``schema=`` on ``on_message`` lands (a deliberate fast-follow).
"""
from __future__ import annotations

import re
from http import HTTPMethod
from typing import Any

from ..extension import Extension

# Pinned CDN release of the AsyncAPI standalone React renderer (parallels the
# Swagger-UI pin in openapi.py).  Loaded from jsdelivr; no new Python dependency.
# Bump freely — the JS bundle and CSS are versioned identically.
_ASYNCAPI_COMPONENT_VERSION = '3.1.3'

_DEFAULT_DESCRIPTION = (
    'Generated by BlackBull. Documents the MQTT topic taps this application '
    'registered via @mqtt.on_message — i.e. what the app observes, not the '
    "broker's full API (a broker accepts any topic). QoS/retain are not "
    'captured, and payloads are opaque bytes until a tap declares a schema.'
)

# Every documented payload references this one component message: opaque MQTT
# bytes.  Richer schemas arrive with the optional on_message ``schema=`` work.
_BYTES_MESSAGE_KEY = 'bytesPayload'


def _camel(words: list[str]) -> str:
    """``['sensors', 'room']`` → ``'sensorsRoom'`` (lowerCamelCase, sanitised)."""
    cleaned = [re.sub(r'[^0-9a-zA-Z]', '', w) for w in words]
    cleaned = [w for w in cleaned if w]
    if not cleaned:
        return ''
    head, *tail = cleaned
    return head[:1].lower() + head[1:] + ''.join(w[:1].upper() + w[1:] for w in tail)


def _channel_id(topic: str) -> str:
    """Derive a readable channel id from a topic filter.

    Wildcard levels (``+``, ``#``) are dropped; ``{name}`` captures contribute
    their name.  ``'sensors/{room}/temperature'`` → ``'sensorsRoomTemperature'``;
    ``'#'`` (nothing left) → ``'root'``.
    """
    words: list[str] = []
    for level in topic.split('/'):
        if level in ('+', '#'):
            continue
        if len(level) >= 2 and level[0] == '{' and level[-1] == '}':
            words.append(level[1:-1])
        else:
            words.append(level)
    return _camel(words) or 'root'


def _operation_id(callback: Any) -> str:
    """Derive an operation id from the tap callback's ``__name__``."""
    name = getattr(callback, '__name__', '') or ''
    name = re.sub(r'[^0-9a-zA-Z_]', '', name)
    return name or 'onMessage'


def _unique(base: str, used: set[str]) -> str:
    """Return *base*, suffixing ``2``, ``3``, … until it is not already in *used*."""
    candidate, n = base, 2
    while candidate in used:
        candidate = f'{base}{n}'
        n += 1
    used.add(candidate)
    return candidate


def _summary(callback: Any) -> str:
    """First line of the callback's docstring, or ``''``."""
    import inspect  # noqa: PLC0415
    doc = inspect.getdoc(callback)
    return doc.splitlines()[0].strip() if doc else ''


def generate_asyncapi(mqtt, *, title: str, version: str,
                      description: str | None, server_host: str) -> dict:
    """Build an AsyncAPI 3.0 document for *mqtt*'s registered ``on_message`` taps.

    *mqtt* is an ``MQTTExtension`` (anything exposing ``iter_subscriptions()``
    and ``port``).  The returned dict is JSON-serialisable.
    """
    doc: dict[str, Any] = {
        'asyncapi': '3.0.0',
        'info': {
            'title': title,
            'version': version,
            'description': description or _DEFAULT_DESCRIPTION,
        },
        'servers': {
            'broker': {
                'host': server_host,
                'protocol': 'mqtt',
                'protocolVersion': '5.0',
            },
        },
        'channels': {},
        'operations': {},
    }

    used_channels: set[str] = set()
    used_ops: set[str] = set()
    for sub in mqtt.iter_subscriptions():
        chan_id = _unique(_channel_id(sub.topic), used_channels)
        doc['channels'][chan_id] = {
            'address': sub.topic,
            'messages': {
                'message': {'$ref': f'#/components/messages/{_BYTES_MESSAGE_KEY}'},
            },
        }
        op_id = _unique(_operation_id(sub.callback), used_ops)
        operation: dict[str, Any] = {
            'action': 'receive',  # POV is the application: it receives PUBLISHes
            'channel': {'$ref': f'#/channels/{chan_id}'},
            'messages': [{'$ref': f'#/channels/{chan_id}/messages/message'}],
        }
        summary = _summary(sub.callback)
        if summary:
            operation['summary'] = summary
        doc['operations'][op_id] = operation

    # Only declare the shared payload component when something references it.
    if doc['channels']:
        doc['components'] = {
            'messages': {
                _BYTES_MESSAGE_KEY: {
                    'name': _BYTES_MESSAGE_KEY,
                    'title': 'Opaque MQTT payload',
                    'contentType': 'application/octet-stream',
                    'payload': {
                        'type': 'string',
                        'format': 'binary',
                        'description': 'Raw MQTT payload bytes (no schema declared).',
                    },
                },
            },
        }
    return doc


_ASYNCAPI_HTML = """\
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{title}</title>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@asyncapi/react-component@{version}/styles/default.min.css">
</head>
<body>
<div id="asyncapi"></div>
<script src="https://cdn.jsdelivr.net/npm/@asyncapi/react-component@{version}/browser/standalone/index.js"></script>
<script>
AsyncApiStandalone.render({{
  schema: {{ url: "{spec_url}" }},
  config: {{ show: {{ sidebar: true, errors: true }} }},
}}, document.getElementById('asyncapi'));
</script>
</body>
</html>
"""


def asyncapi_html(spec_url: str, title: str = 'BlackBull — AsyncAPI') -> str:
    """Return a self-contained HTML page hosting the AsyncAPI renderer."""
    return _ASYNCAPI_HTML.format(
        title=title, version=_ASYNCAPI_COMPONENT_VERSION, spec_url=spec_url)


class AsyncAPIExtension(Extension):
    """Mount an AsyncAPI 3.0 spec endpoint (+ HTML viewer) describing the MQTT taps.

    Requires an ``MQTTExtension`` on the same app; it is read lazily (per
    request) via ``app.extensions['mqtt']``, so there is **no ordering
    constraint** at registration — and taps added *after* this extension are
    still documented.  The MQTT extension must, however, be present when the
    spec route is hit, or the request raises ``RuntimeError``.

    Two GET routes are registered (mirroring ``OpenAPIExtension``):

    * ``spec_path`` (default ``/asyncapi.json``) → the document as JSON;
    * ``docs_path`` (default ``/asyncapi``, ``None`` to skip) → an HTML page
      hosting the CDN AsyncAPI renderer.
    """

    extension_key = 'asyncapi'

    def __init__(self, app: object | None = None, *,
                 title: str = 'BlackBull MQTT API',
                 version: str = '0.1.0',
                 description: str | None = None,
                 server_host: str | None = None,
                 spec_path: str = '/asyncapi.json',
                 docs_path: str | None = '/asyncapi') -> None:
        self.title = title
        self.version = version
        self.description = description
        self.server_host = server_host
        self.spec_path = spec_path
        self.docs_path = docs_path
        # Hold strong refs to the registered handlers (see OpenAPIExtension).
        self._spec_handler = None
        self._docs_handler = None
        if app is not None:
            self.init_app(app)

    def _generate(self, app) -> dict:
        mqtt = app.extensions.get('mqtt')
        if mqtt is None:
            raise RuntimeError(
                'AsyncAPIExtension requires an MQTTExtension on the app; '
                'call app.add_extension(MQTTExtension(...)) as well.')
        host = self.server_host or f'localhost:{getattr(mqtt, "port", 1883)}'
        return generate_asyncapi(
            mqtt, title=self.title, version=self.version,
            description=self.description, server_host=host)

    def init_app(self, app) -> None:
        """Wire the spec + docs routes onto *app* through the public API."""
        from ..response import Response, JSONResponse  # noqa: PLC0415

        self._register(app)

        spec_path, docs_path = self.spec_path, self.docs_path

        async def _asyncapi_spec(scope, receive, send):  # noqa: ARG001
            await send(JSONResponse(self._generate(app)))
        # Flag so a *future* AsyncAPI-aware generator never documents itself;
        # set before registration so the original handler carries the attribute
        # (functools.wraps does not copy it onto the wrapper).
        _asyncapi_spec.__blackbull_asyncapi_internal__ = True
        app.route(methods=HTTPMethod.GET, path=spec_path)(_asyncapi_spec)
        self._spec_handler = _asyncapi_spec

        if docs_path is not None:
            ui_title = f'{self.title} — AsyncAPI'

            async def _asyncapi_docs(scope, receive, send):  # noqa: ARG001
                await send(Response(asyncapi_html(spec_path, title=ui_title)))
            _asyncapi_docs.__blackbull_asyncapi_internal__ = True
            app.route(methods=HTTPMethod.GET, path=docs_path)(_asyncapi_docs)
            self._docs_handler = _asyncapi_docs
